version: "3.9"

services:
  srs:
    image: ossrs/srs:6
    container_name: srs-server
    ports:
      - "1935:1935"
      - "1985:1985"
    volumes:
      - ./srs.conf:/usr/local/srs/conf/docker.conf # ‚Üê Cambia esto
    restart: always
    networks:
      - srs-network
    ulimits:
      nofile:
        soft: 100000
        hard: 100000

  backend-go:
    build: .
    container_name: backend-go
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./thumbnails:/app/thumbnails
    restart: always
    depends_on:
      - srs
    networks:
      - srs-network

networks:
  srs-network:
    driver: bridge
