version: "3.9"

services:
  srs:
    image: ossrs/srs:6
    container_name: srs-server
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
    volumes:
      - ./srs.conf:/usr/local/srs/conf/docker.conf
    restart: always
    networks:
      - srs-network
    ulimits:
      nofile:
        soft: 100000
        hard: 100000

  backend-go:
    build: .
    container_name: backend-go
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./thumbnails:/app/thumbnails
    restart: always
    depends_on:
      - srs
    networks:
      - srs-network

  nginx:
    image: nginx:alpine
    container_name: nginx-thumbnails
    ports:
      - "80:80" # ‚Üê PUERTO 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./thumbnails:/usr/share/nginx/html/thumbnails:ro
    restart: always
    networks:
      - srs-network

networks:
  srs-network:
    driver: bridge
